#!/bin/bash
cat index.html | perl -wpe 's/([\\"])/\\$1/g' | sed -e 's/$/ \\/'   | (echo -n "\$(\"body\").html(\""  && cat) | (cat && echo  " <script src='\"+rootUrl+\"/scriptAfterLoaded.js'> </script>\\"  ) | (cat && echo  " <link rel='stylesheet' href='\"+rootUrl+\"/design.css'/>\");"  )  |  cat > index.js

