#!/bin/bash
cat "Forum des Jeunes Écrivains :: Smileys.html" | perl -wpe 's/([\\"])/\\$1/g' | sed -e 's/$/ \\/'   | (echo -n "function openSmiley(event){processSmileyAndDisplay(\""  && cat) | (cat && echo  " \");}"  )  |  cat > index.js

